baseURL = "https://responsible.org"
languageCode = "en-us"
title = "Responsible.org"
summaryLength = "20"
paginate = "5"

[[module.mounts]]
source = "static"
target = "static"

[[module.mounts]]
source = "static/images"
target = "static/images"

[[module.imports]]
path = "github.com/themefisher/parsa-hugo"

  [[module.imports.mounts]]
  source = "layouts"
  target = "layouts"

  [[module.imports.mounts]]
  source = "assets"
  target = "assets"

  [[module.imports.mounts]]
  source = "static"
  target = "static"

  [[module.imports.mounts]]
  source = "exampleSite/static/images"
  target = "static/images"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
logo = "images/responsible.org.logo.medium.png"
home = "Home"
layout = "2"
description = "Responsible.org Website"
preloader = true
search = true
author = "Responsible.org"
author_image = "images/nathan-dumlao-4_mJ1TbMK8A-unsplash.jpg"
bio = """
Responsible.org&trade; promotes responsible gun purchase, ownership, and use. We
feature information on public policy and legislative issues as well as research
services in the field. We also organize educational events focused on responsible
gun ownership. We conduct virtual and in-person seminars, lectures, workshops,
panel discussions and forums.
"""
mobile = "(307) 463-1680"
email = "info@responsible.org"
address = "15433 NE 95th St, Redmond, WA 98052"
contact_form_action = "#"
google_analytics_id = "Your ID"
copyright = "Copyright &copy; 2018-2020 Responsible.org&trade;.Theme by [themefisher.com](https://themefisher.com)"

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

[params.instafeed]
enable = false
access_token = "IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn"

  [[params.social]]
  icon = "ti-facebook"
  URL = "https://facebook.com"

  [[params.social]]
  icon = "ti-twitter-alt"
  URL = "https://twitter.com"

  [[params.social]]
  icon = "ti-linkedin"
  URL = "https://linkedin.com"

  [[params.social]]
  icon = "ti-github"
  URL = "https://github.com/responsible-org"

[[menu.main]]
name = "About"
URL = "about"
weight = "2"

[[menu.main]]
name = "Contact"
URL = "contact"
weight = "3"
