---
baseURL: "/"
languageCode: en-us
title: Responsible.org
module:
  imports:
  - path: github.com/themefisher/parsa-hugo
    mounts:
    - source: layouts
      target: layouts
    - source: assets
      target: assets
    - source: static
      target: static
    - source: exampleSite/static/images
      target: static/images
summaryLength: "10"
paginate: "6"
outputs:
  home:
  - HTML
  - RSS
  - JSON
params:
  plugins:
    css:
    - link: plugins/bootstrap/bootstrap.min.css
    - link: plugins/slick/slick.css
    - link: plugins/themify-icons/themify-icons.css
    js:
    - link: plugins/jQuery/jquery.min.js
    - link: plugins/bootstrap/bootstrap.min.js
    - link: plugins/slick/slick.min.js
    - link: plugins/headroom/headroom.js
    - link: plugins/instafeed/instafeed.min.js
    - link: plugins/masonry/masonry.js
    - link: plugins/reading-time/readingTime.min.js
    - link: plugins/smooth-scroll/smooth-scroll.js
    - link: plugins/search/fuse.min.js
    - link: plugins/search/mark.js
    - link: plugins/search/search.js
  logo: images/logo.png
  home: Home
  layout: "2"
  description: This is meta description
  preloader: true
  search: true
  author: Responsible.org
  author_image: images/banner-img.png
  bio: |
    Responsible.org promotes responsible gun purchase, ownership, and use. We
    feature information on public policy and legislative issues as well as research
    services in the field. We also organize educational events focused on responsible
    gun ownership. We conduct virtual and in-person seminars, lectures, workshops,
    panel discussions and forums.
  mobile: "(307) 463-1680"
  email: info@responsible.org
  address: 15433 NE 95th St, Redmond, WA 98052
  contact_form_action: "#"
  google_analitycs_id: Your ID
  copyright: |
    Copyright &copy; 2018-2020 Responsible.org.
    Theme by [themefisher.com](https://themefisher.com)
  instafeed:
    enable: true
    access_token: IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn
  social:
  - icon: ti-facebook
    URL: https://facebook.com
  - icon: ti-twitter-alt
    URL: https://twitter.com
  - icon: ti-linkedin
    URL: https://linkedin.com
  - icon: ti-github
    URL: https://github.com/responsible-org
menu:
  main:
  - name: About
    URL: about
    weight: "2"
  - name: Contact
    URL: contact
    weight: "3"
